Homeworks 3 1 3 2
gerganaivvanova/swiftui_project pull request #5
Opened 2023-06-29 20:49 UTC by gerganaivvanova

You can find the video of the app in the ReadMe file of the repository.

2023-06-29 21:36 UTC, yll090 requested changes

2023-06-29 21:36 UTC, yll090 commented on swiftui-project/View/HomeScreen/Filters/PriceRangeFilters.swift
> +                    upperThumbSize: CGSize(width: UIConstants.rangeFilterWidth, height: UIConstants.rangeFilterWidth),
You could reuse these, as well as the thumb values.

2023-06-29 21:36 UTC, yll090 commented on swiftui-project/View/CartScreen/CartScreenView.swift
> +                            message: Text("Are you sure you want to proceed to check out?"),
Not sure if we've missed it or you or we all have and if we're to blame we're terribly sorry, but strings need to be exported and reused via keys. You have the `Localizable` files, but they're empty. You need to export all strings throughout the app.

2023-06-29 21:36 UTC, yll090 commented on swiftui-project/View/ProfileScreen/ProfileView.swift
> +                .frame(width: 100, height: 100)
Extract to a constants file.

2023-06-29 21:36 UTC, yll090 commented on swiftui-project/View/ProfileScreen/ProfileView.swift
> +                navigateToLogIn = true}){
I think this is part of the next homework, but since you're already here -- you should clean up the user token here.

2023-06-30 08:28 UTC, StefanPanayotov commented on swiftui-project/View/ProductDetails/ProductViewModel.swift
> +    func reduceStock(for product: Product) -> Product {
why is this needed can you just decrement the Product ?

2023-06-30 09:48 UTC, gbuyukliev-accedia approved these changes
A few comments.

2023-06-30 09:48 UTC, gbuyukliev-accedia commented on swiftui-project/View/HomeScreen/Filters/CategoryFilters.swift
> +                    Button(
Always extract list item layouts to separate structs, no matter how small they are. If it's small like that one it can even be down in the very same file.

2023-06-30 09:48 UTC, gbuyukliev-accedia commented on swiftui-project/View/HomeScreen/Filters/PriceRangeFilters.swift
> +                Text(String(format: "$%.2f", selectedPriceRange.lowerBound))
Extract `"$%.2f"` to a constant.

2023-06-30 09:48 UTC, gbuyukliev-accedia commented on swiftui-project/View/HomeScreen/Filters/RatingFilters.swift
> +                    .onTapGesture {
Note: You get no click effect with `.onTapGesture`. To get a click effect you have to use a `Button`. Not sure if that's a desired effect or not here. If it is - it's totally fine.

2023-06-30 09:48 UTC, gbuyukliev-accedia commented on swiftui-project/View/HomeScreen/HomeScreenView.swift
> +                            Text("\(allProductsModel.appliedFilterCount)")
The styling here looks like a candidate to be extracted as a `ViewModifier` - it will become a lot less compact with the option for reuse.

2023-06-30 09:48 UTC, gbuyukliev-accedia commented on swiftui-project/View/HomeScreen/HomeScreenView.swift
> +                NavigationLink(destination: ProfileView()){
Using `NavigationLink` for navigation is fine but with it you can't add an element to your navigation `path` env property. Wouldn't that present issues when you try to log out the user straight to the Login screen, clearing all other screens from the stack?

2023-06-30 09:48 UTC, gbuyukliev-accedia commented on swiftui-project/View/Layouts/CartButton.swift
> +                    Text("\(productsCounter)")
Same styling on the `Text` here as the above comment - the `ViewModifier` will help with the reusability here greatly.

2023-06-30 09:48 UTC, gbuyukliev-accedia commented on swiftui-project/View/Layouts/CartItem.swift
> +                    Text(String(format: "$%.2f", Double(product.price)))
You can use the constant for `$%.2f` that you've extracted here to guarantee a single source of truth throughout the whole app.

2023-06-30 09:48 UTC, gbuyukliev-accedia commented on swiftui-project/View/Layouts/CartItem.swift
> +                    Text("Quantity: 1")
Shouldn't the value here be dynamic? Also, the text should be extracted to `Localizable` as @yll090 said. There should be no hardcoded values of any kind in the project. It's not necessary to extract all hardcoded texts at this point but at least just a few to get a feel of the process.

2023-06-30 09:48 UTC, gbuyukliev-accedia commented on swiftui-project/View/ProductDetails/ProductDetailsView.swift
> +                            if(product.stock > 0 ){
Nothing wrong with that. Just an alternative approach that's perhaps a bit more structured and easily readable:

```
var isInStock: Bool {
  return product.stock > 0
}

var stockText: String {
  return isInStock ? "In stock" : "Out of stock"
}

var stockColor: Color {
  return isInStock ? Color("Black") : Color("ErrorColor")
}

...

HStack(spacing: UIConstants.spacing) {
  if inStock {
    Image(systemName: "checkmark.circle.fill")
      .foregroundColor(.green)
  }

  Text(stockText).foregroundColor(stockColor)
}
```

2023-06-30 09:48 UTC, gbuyukliev-accedia commented on swiftui-project/View/ProfileScreen/ProfileView.swift
> +                    Text("Log out")
Export styling to a `ViewModifier`.

2023-06-30 09:48 UTC, gbuyukliev-accedia commented on swiftui-project/View/ProfileScreen/ProfileView.swift
> +        .navigationDestination(isPresented: $navigateToLogIn, destination: {LoginView()})
I don't think you are clearing the other screens like that. They will be most likely under the `LoginView`. You have to add screens to your `path` exposed via an `EnvironmentObject` on every navigation and then upon logging out just clear out all elements from the `path` array except the first one, which would be the LoginView.

2023-11-22 08:30 UTC, merged